ShoppingCartMVC/Controllers/CartItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShoppingCartMVC.DAL;
using ShoppingCartMVC.Models;

namespace ShoppingCartMVC.Controllers
{
    public class CartItemController : Controller
    {
        public string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        private ShoppingCartContext db = new ShoppingCartContext();



        public ActionResult CheckOut()
        {
            return View();
        }



        public ActionResult Done(Checkout checkout)
        {
            ShoppingCartId = GetCartId();
            checkout.Total = db.CartItem.Where(c => c.CartId == ShoppingCartId).Sum(n => n.Quantity * n.Item.Price);
            checkout.Items = db.CartItem.Where(c => c.CartId == ShoppingCartId).ToList();
            checkout.OrderDate = DateTime.Now;

            db.Checkouts.Add(checkout);
            db.SaveChanges();

            return View(checkout);
        }
        public ActionResult Index()
        {
            ShoppingCartId = GetCartId();
            if (User.Identity.Name == "admin")
            {
                return View(db.CartItem.ToList());
            }
            else
            {
                return View(db.CartItem?.Where(x => x.CartId == ShoppingCartId).ToList());
            }
        }

        public ActionResult Increase(int id)
        {
            ShoppingCartId = GetCartId();

            var cartItem = db.CartItem.SingleOrDefault(
            c => c.CartId == ShoppingCartId
            && c.ItemId == id);

            cartItem.Quantity++;
            db.SaveChanges();
            return RedirectToAction("Index");


        }

        public ActionResult AddToCart(int id)
        {
            ShoppingCartId = GetCartId();

             var cartItem = db.CartItem.SingleOrDefault(
             c => c.CartId == ShoppingCartId
             && c.ItemId == id);
            if (cartItem == null)
            {
                              
                cartItem = new CartItem
                {
                    CartItemId = Guid.NewGuid().ToString(),
                    ItemId = id,
                    CartId = ShoppingCartId,
                    Item = db.Items.SingleOrDefault(
                    p => p.ItemId == id),
                    Quantity = 1,
                    
                };

                db.CartItem.Add(cartItem);
            }
            else
            {
                cartItem.Quantity++;
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public string GetCartId()
        {          
                return System.Web.HttpContext.Current.User.Identity.Name.ToString();
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = db.CartItem.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            db.CartItem.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }

       
    
}

ShoppingCartMVC/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShoppingCartMVC.DAL;
using ShoppingCartMVC.Models;

namespace ShoppingCartMVC.Controllers
{
    public class CategoryController : Controller
    {
        private ShoppingCartContext db = new ShoppingCartContext();

        // GET: Category
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CatName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CatName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShoppingCartMVC/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShoppingCartMVC.DAL;
using ShoppingCartMVC.Models;


namespace ShoppingCartMVC.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private ShoppingCartContext db = new ShoppingCartContext();

        private SearchRepository searchRepository = new SearchRepository();


        // GET: Item
        public ActionResult Index()
        {
            var items = db.Items.ToList();
            return View(items);
        }

        public ViewResult Search(string searchtext)
        {
            var items = searchRepository.Search(searchtext);

            return View(items);
        }





        // GET: Item/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Item/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Item/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemId,ItemName,CatId,Price,Description,ImagePath")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Item/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Item/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemId,ItemName,CatId,Price,Description,ImagePath")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Item/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShoppingCartMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ShoppingCartMVC</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
   
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("ShoppingCart", "Index", "Item", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Categories", "Index", "Category", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Cart", "Index", "CartItem", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                </ul>
                <form action="@Url.Action("Search", "Item")" class="d-flex">
                    <input class="form-control me-2" name="searchtext" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <div style="margin:0px 10px">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li style="color:white">Dear - @User.Identity.Name</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                </div>
                
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ShoppingCartMVC</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>